name: Pull request
on:
  pull_request:
    branches:
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Set up node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        run: yarn lint
